tags = [
    {"ru_name": "Азартные игры", "en_name": "Gambling"},
    {"ru_name": "Алхимия", "en_name": "Alchemy"},
    {"ru_name": "Амнезия / Потеря памяти", "en_name": "Amnesia / Memory Loss"},
    {"ru_name": "Ангелы", "en_name": "Angels"},
    {"ru_name": "Антигерой", "en_name": "Antihero"},
    {"ru_name": "Антиутопия", "en_name": "Dystopia"},
    {"ru_name": "Апокалипсис", "en_name": "Apocalypse"},
    {"ru_name": "Армия", "en_name": "Army"},
    {"ru_name": "Артефакты", "en_name": "Artifacts"},
    {"ru_name": "Боги", "en_name": "Gods"},
    {"ru_name": "Бои на мечах", "en_name": "Sword Fighting"},
    {"ru_name": "Борьба за власть", "en_name": "Power Struggle"},
    {"ru_name": "Брат и сестра", "en_name": "Brother and Sister"},
    {"ru_name": "Будущее", "en_name": "Future"},
    {"ru_name": "Ведьма", "en_name": "Witch"},
    {"ru_name": "Вестерн", "en_name": "Western"},
    {"ru_name": "Видеоигры", "en_name": "Video Games"},
    {"ru_name": "Виртуальная реальность", "en_name": "Virtual Reality"},
    {"ru_name": "Владыка демонов", "en_name": "Demon Lord"},
    {"ru_name": "Военные", "en_name": "Military"},
    {"ru_name": "Война", "en_name": "War"},
    {"ru_name": "Волшебники / маги", "en_name": "Wizards / Mages"},
    {"ru_name": "Волшебные существа", "en_name": "Magical Creatures"},
    {"ru_name": "Воспоминания из другого мира", "en_name": "Memories from Another World"},
    {"ru_name": "Выживание", "en_name": "Survival"},
    {"ru_name": "ГГ женщина", "en_name": "Female MC"},
    {"ru_name": "ГГ имба", "en_name": "IMBA MC"},
    {"ru_name": "ГГ мужчина", "en_name": "Male MC"},
    {"ru_name": "Геймеры", "en_name": "Gamers"},
    {"ru_name": "Гильдии", "en_name": "Guilds"},
    {"ru_name": "Глупый ГГ", "en_name": "Stupid MC"},
    {"ru_name": "Гоблины", "en_name": "Goblins"},
    {"ru_name": "Горничные", "en_name": "Maids"},
    {"ru_name": "Гяру", "en_name": "Gyaru"},
    {"ru_name": "Демоны", "en_name": "Demons"},
    {"ru_name": "Драконы", "en_name": "Dragons"},
    {"ru_name": "Дружба", "en_name": "Friendship"},
    {"ru_name": "Жестокий мир", "en_name": "Cruel World"},
    {"ru_name": "Животные компаньоны", "en_name": "Animal Companions"},
    {"ru_name": "Завоевание мира", "en_name": "Conquest world"},
    {"ru_name": "Зверолюди", "en_name": "Beastmen"},
    {"ru_name": "Злые духи", "en_name": "Evil spirits"},
    {"ru_name": "Зомби", "en_name": "Zombies"},
    {"ru_name": "Игровые элементы", "en_name": "Game elements"},
    {"ru_name": "Империи", "en_name": "Empires"},
    {"ru_name": "Камера", "en_name": "Camera"},
    {"ru_name": "Квесты", "en_name": "Quests"},
    {"ru_name": "Космос", "en_name": "Space"},
    {"ru_name": "Кулинария", "en_name": "Cooking"},
    {"ru_name": "Культивация", "en_name": "Cultivation"},
    {"ru_name": "Легендарное оружие", "en_name": "Legendary weapons"},
    {"ru_name": "Лоли", "en_name": "Loli"},
    {"ru_name": "Магическая академия", "en_name": "Magic academy"},
    {"ru_name": "Магия", "en_name": "Magick"},
    {"ru_name": "Мафия", "en_name": "Mafia"},
    {"ru_name": "Медицина", "en_name": "Medicine"},
    {"ru_name": "Месть", "en_name": "Revenge"},
    {"ru_name": "Монстродевушки", "en_name": "Monster girls"},
    {"ru_name": "Монстры", "en_name": "Monsters"},
    {"ru_name": "Музыка", "en_name": "Music"},
    {"ru_name": "Навыки / способности", "en_name": "Skills / abilities"},
    {"ru_name": "Насилие / жестокость", "en_name": "Violence / cruelty"},
    {"ru_name": "Наёмники", "en_name": "Mercenaries"},
    {"ru_name": "Нежить", "en_name": "Undead"},
    {"ru_name": "Ниндзя", "en_name": "Ninja"},
    {"ru_name": "Обмен телами", "en_name": "Body swap"},
    {"ru_name": "Обратный Гарем", "en_name": "Reverse Harem"},
    {"ru_name": "Огнестрельное оружие", "en_name": "Firearms"},
    {"ru_name": "Офисные Работники", "en_name": "Office workers"},
    {"ru_name": "Пародия", "en_name": "Parody"},
    {"ru_name": "Пираты", "en_name": "Pirates"},
    {"ru_name": "Подземелья", "en_name": "Dungeons"},
    {"ru_name": "Политика", "en_name": "Politics"},
    {"ru_name": "Полиция", "en_name": "Police"},
    {"ru_name": "Преступники / Криминал", "en_name": "Criminals / Crime"},
    {"ru_name": "Призраки / Духи", "en_name": "Ghosts / Spirits"},
    {"ru_name": "Путешествие во времени", "en_name": "Time travel"},
    {"ru_name": "Рабы", "en_name": "Slaves"},
    {"ru_name": "Разумные расы", "en_name": "Intelligent races"},
    {"ru_name": "Ранги силы", "en_name": "Power ranks"},
    {"ru_name": "Реинкарнация", "en_name": "Reincarnation"},
    {"ru_name": "Роботы", "en_name": "Robots"},
    {"ru_name": "Рыцари ", "en_name": "Knights"},
    {"ru_name": "Самураи", "en_name": "Samurai"},
    {"ru_name": "Система", "en_name": "System"},
    {"ru_name": "Скрытие личности", "en_name": "Identity hiding"},
    {"ru_name": "Спасение мира", "en_name": "Saving the world"},
    {"ru_name": "Спортивное тело", "en_name": "Sports body"},
    {"ru_name": "Средневековье", "en_name": "Middle Ages"},
    {"ru_name": "Стимпанк", "en_name": "Steampunk"},
    {"ru_name": "Супергерои", "en_name": "Superheroes"},
    {"ru_name": "Традиционные игры", "en_name": "Traditional games"},
    {"ru_name": "Умный ГГ", "en_name": "Smart MC"},
    {"ru_name": "Учитель  / ученик", "en_name": "Teacher / student"},
    {"ru_name": "Философия", "en_name": "Philosophy"},
    {"ru_name": "Хиккикомори", "en_name": "Hikkikomori"},
    {"ru_name": "Холодное оружие", "en_name": "Cold weapons"},
    {"ru_name": "Шантаж", "en_name": "Blackmail"},
    {"ru_name": "Эльфы", "en_name": "Elves"},
    {"ru_name": "Якудза", "en_name": "Yakuza"},
    {"ru_name": "Яндере", "en_name": "Yandere"},
    {"ru_name": "Япония", "en_name": "Japan"},
]

jenres = [
    {"ru_name": "Арт", "en_name": "Art"},
    {"ru_name": "Безумие", "en_name": "Madness"},
    {"ru_name": "Боевик", "en_name": "Action"},
    {"ru_name": "Боевые искусства", "en_name": "Martial arts"},
    {"ru_name": "Вампиры", "en_name": "Vampires"},
    {"ru_name": "Военное", "en_name": "War"},
    {"ru_name": "Гарем", "en_name": "Harem"},
    {"ru_name": "Гендерная интрига", "en_name": "Gender intrigue"},
    {"ru_name": "Героическое фентези", "en_name": "Heroic fantasy"},
    {"ru_name": "Демоны", "en_name": "Demons"},
    {"ru_name": "Детектив", "en_name": "Detective"},
    {"ru_name": "Детское", "en_name": "Children's"},
    {"ru_name": "Дзёсай", "en_name": "Josai"},
    {"ru_name": "Драма", "en_name": "Drama"},
    {"ru_name": "Игра", "en_name": "Game"},
    {"ru_name": "Исекай", "en_name": "Isekai"},
    {"ru_name": "История", "en_name": "History"},
    {"ru_name": "Киберпанк", "en_name": "Cyberpunk"},
    {"ru_name": "Кодомо", "en_name": "Kodomo"},
    {"ru_name": "Комедия", "en_name": "Comedy"},
    {"ru_name": "Космос", "en_name": "Space"},
    {"ru_name": "Магия", "en_name": "Magic"},
    {"ru_name": "Махо-сёдзё", "en_name": "Maho-shoujo"},
    {"ru_name": "Машины", "en_name": "Cars"},
    {"ru_name": "Меха", "en_name": "Mecha"},
    {"ru_name": "Мистика", "en_name": "Mysticism"},
    {"ru_name": "Музыка", "en_name": "Music"},
    {"ru_name": "Научная фантастика", "en_name": "Sci-fi"},
    {"ru_name": "Омегаверс", "en_name": "Omegaverse"},
    {"ru_name": "Пародия", "en_name": "Parody"},
    {"ru_name": "Повседневность", "en_name": "Everyday life"},
    {"ru_name": "Полиция", "en_name": "Police"},
    {"ru_name": "Постапокалиптика", "en_name": "Post-apocalyptic"},
    {"ru_name": "Приключения", "en_name": "Adventure"},
    {"ru_name": "Психология", "en_name": "Psychology"},
    {"ru_name": "Романтика", "en_name": "Romance"},
    {"ru_name": "Самурайский боевик", "en_name": "Samurai action"},
    {"ru_name": "Сверхъестественное", "en_name": "Supernatural"},
    {"ru_name": "Сёдзё", "en_name": "Shoujo"},
    {"ru_name": "Сёдзё-ай", "en_name": "Shoujo-ai"},
    {"ru_name": "Сёнен", "en_name": "Shonen"},
    {"ru_name": "Сёнен-ай", "en_name": "Shonen-ai"},
    {"ru_name": "Спорт", "en_name": "Sports"},
    {"ru_name": "Супер сила", "en_name": "Super power"},
    {"ru_name": "Сэйнен", "en_name": "Seinen"},
    {"ru_name": "Трагедия", "en_name": "Tragedy"},
    {"ru_name": "Триллер", "en_name": "Thriller"},
    {"ru_name": "Ужасы", "en_name": "Horror"},
    {"ru_name": "Фантастика", "en_name": "Sci-Fi"},
    {"ru_name": "Фэнтези", "en_name": "Fantasy"},
    {"ru_name": "Школа", "en_name": "School"},
    {"ru_name": "Этти", "en_name": "Ecchi"},
    {"ru_name": "Юри", "en_name": "Yuri"}
]


roles = [
    {"ru_name": "Ограниченный", "en_name": "Restricted", "ru_desc": "крутой", "en_desc": "cool"},           #0 
    {"ru_name": "Пользователь", "en_name": "User", "ru_desc": "крутой", "en_desc": "cool"},                 #1 POST_COMMENT RATE_COMMENT REPORT_COMMENT RATE_TITLE REPORT_TITLE POST_TITLE
    {"ru_name": "Модератор", "en_name": "Moderator", "ru_desc": "крутой", "en_desc": "cool"},               #2 POST_COMMENT DELETE_COMMENT RATE_COMMENT REPORT_COMMENT RATE_TITLE REPORT_TITLE POST_TITLE RESTRICT_USER
    {"ru_name": "Модератор тайтлов", "en_name": "Title moderator", "ru_desc": "крутой", "en_desc": "cool"}, #3 POST_COMMENT RATE_COMMENT REPORT_COMMENT RATE_TITLE REPORT_TITLE POST_TITLE APPROVE_TITLE DISAPPROVE_TITLE EDIT_TITLE_DATA 
    {"ru_name": "Администратор", "en_name": "Admin", "ru_desc": "крутой", "en_desc": "cool"}                #4 POST_COMMENT DELETE_COMMENT RATE_COMMENT REPORT_COMMENT RATE_TITLE REPORT_TITLE POST_TITLE APPROVE_TITLE DISAPPROVE_TITLE EDIT_TITLE_DATA RESTRICT_USER CHANGE_USER_ROLES EDIT_USER_DATA
]

priviledges = [
    # COMMENT
    {"name": "POST_COMMENT"},              #0 возможность писать, удалять и редактировать свои комментарии
    {"name": "DELETE_COMMENT"},            #1 возможность удалять чужие комментарии
    {"name": "RATE_COMMENT"},              #2 возможность оценивать комментарии
    {"name": "REPORT_COMMENT"},            #3 возможность жаловаться на комментарии
    # TITLE
    {"name": "RATE_TITLE"},                #4 возможность оценивать тайтлы
    {"name": "REPORT_TITLE"},              #5 возможность жаловаться на тайтлы
    {"name": "POST_TITLE"},                #6 возможность отправлять тайтлы на модерацию
    {"name": "APPROVE_TITLE"},             #7 возможность делать тайтлы общедоступными(выводить из статуса pending)
    {"name": "DISAPPROVE_TITLE"},          #8 возможность скрывать тайтлы от глаз(выводить из статуса release)
    {"name": "EDIT_TITLE_DATA"},           #9 возможность менять данные тайтла
    # USER
    {"name": "RESTRICT_USER"},             #10 возможность ограничивать пользователя (снижать его роль до Restricted на определенное время)
    {"name": "CHANGE_USER_ROLES"},         #11 возможность менять роль пользователя
    {"name": "EDIT_USER_DATA"}             #12 возможность менять общедоступные-данные пользователя
]

role_priviledges = [
    # пользователь
    {"role_id": 1, "priviledge_id": 0}, 
    {"role_id": 1, "priviledge_id": 2},
    {"role_id": 1, "priviledge_id": 3},
    {"role_id": 1, "priviledge_id": 4},
    {"role_id": 1, "priviledge_id": 5},
    {"role_id": 1, "priviledge_id": 6},
    # модератор
    {"role_id": 2, "priviledge_id": 0}, 
    {"role_id": 2, "priviledge_id": 1}, 
    {"role_id": 2, "priviledge_id": 2},
    {"role_id": 2, "priviledge_id": 3},
    {"role_id": 2, "priviledge_id": 4},
    {"role_id": 2, "priviledge_id": 5},
    {"role_id": 2, "priviledge_id": 6},
    {"role_id": 2, "priviledge_id": 10},
    # модератор тайтлов
    {"role_id": 3, "priviledge_id": 0}, 
    {"role_id": 3, "priviledge_id": 1}, 
    {"role_id": 3, "priviledge_id": 2},
    {"role_id": 3, "priviledge_id": 3},
    {"role_id": 3, "priviledge_id": 4},
    {"role_id": 3, "priviledge_id": 5},
    {"role_id": 3, "priviledge_id": 6},
    {"role_id": 3, "priviledge_id": 7},
    {"role_id": 3, "priviledge_id": 8},
    {"role_id": 3, "priviledge_id": 9},
    # админ
    {"role_id": 4, "priviledge_id": 0}, 
    {"role_id": 4, "priviledge_id": 1}, 
    {"role_id": 4, "priviledge_id": 2},
    {"role_id": 4, "priviledge_id": 3},
    {"role_id": 4, "priviledge_id": 4},
    {"role_id": 4, "priviledge_id": 5},
    {"role_id": 4, "priviledge_id": 6},
    {"role_id": 4, "priviledge_id": 7},
    {"role_id": 4, "priviledge_id": 8},
    {"role_id": 4, "priviledge_id": 9},
    {"role_id": 4, "priviledge_id": 10},
    {"role_id": 4, "priviledge_id": 11},
    {"role_id": 4, "priviledge_id": 12}
]

